# Generated by Django 4.0.4 on 2022-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], default=1, verbose_name='级别'),
        ),
    ]
