# Generated by Django 4.0.4 on 2022-06-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.IntegerField(default=0, verbose_name='价钱')),
                ('status', models.SmallIntegerField(choices=[(1, '已支付'), (2, '待支付')], default=2, verbose_name='状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.admin', verbose_name='管理员')),
            ],
        ),
    ]
